name: Create IU Workbook
description: Create your IU Workbook with GitHub Actions.

inputs:
  # student details
  first_name:
    description: The first name of the student
    required: true
  last_name:
    description: The last name of the student
    required: true
  email:
    description: The email of the student
    required: true
  id:
    description: The id of the student
    required: true
  degree:
    description: The degree pursued by the student
    required: true
    
  # course details
  course_name:
    description: The name of the course
    required: true
  course_id:
    description: The id of the course
    required: true
  professor:
    description: The professor of the course
    required: true
  tutor:
    description: The tutor of the course
    required: true
  
  # workbook details
  workbook:
    description: Path to the workbook.md
    required: true
  
  # configuration details
  content_format_doc:
    description: Path to the Microsoft Word template of the content
    required: true
  cover_format_doc:
    description: Path to the Microsoft Word template of the cover page
    required: true
  cover_template_doc:
    description: Path to the Markdown template of the cover page to define the structure
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create Cover
      if: ${{ success() }}
      uses: iu-actions/workbook-cover@main
      with:
        # student details
        first_name: ${{ inputs.first_name }}
        last_name: ${{ inputs.last_name }}
        email: ${{ inputs.email }}
        id: ${{ inputs.id }}
        degree: ${{ inputs.degree }}

        # course details
        course_name: ${{ inputs.course_name }}
        course_id: ${{ inputs.course_id }}
        professor: ${{ inputs.professor }}
        tutor: ${{ inputs.tutor }}

        # configuration details
        format_doc: ${{ inputs.cover_format_doc }}
        template_doc: ${{ inputs.cover_template_doc }}
    - name: Create Content
      if: ${{ success() }}
      uses: iu-actions/workbook-content@main
      with:
        # workbook details
        workbook: ${{ inputs.workbook }}

        # configuration details
        format_doc: ${{ inputs.content_format_doc }}
    - name: Merge (Cover, Content)
      if: ${{ success() }}
      uses: iu-actions/workbook-merge@main
    - name: Release Workbook
      if: ${{ success() }}
      uses: iu-actions/workbook-release@main
      with:
        # student details
        first_name: ${{ inputs.first_name }}
        last_name: ${{ inputs.last_name }}
        id: ${{ inputs.id }}
        
        # course details
        course_name: ${{ inputs.course_name }}
        course_id: ${{ inputs.course_id }}
